### ISSUE TITLE
retr variable non incremented in non debug mode

### ISSUE THREAD

**Issue by bobboteck** [Cyb3rn0id/Coviclock#1]
Hi @Cyb3rn0id, I wanted to report a possible bug, as you can see in the code, the variable retr is incremented only if the code is run in debug mode.

https://github.com/Cyb3rn0id/Coviclock/blob/8b08d459d170ff029ba662644f06a57464a26baf/firmware/coviclock/coviclock.ino#L183-L188

I think it is enough to move it out of the if control to make it work in all cases.

**Comment by Cyb3rn0id** [comment]
Solved: https://github.com/Cyb3rn0id/Coviclock/commit/07fdd81981882316e8827cfad18bd184998b28d6
